export const infoData = {
  baseApi: "https://api.vaahansafety.org/api",
};

const tempCompanies = [
  "DAIMLER INDIA COMMERCIAL VEHICLE",
  "ASHOK LEYLAND",
  "ASIA MOTORS",
  "BAJAJ",
  "FORCE MOTORS",
  "FORD",
  "GENERAL MOTORS",
  "HINDUSTAN MOTORS",
  "HONDA",
  "HYUNDAI",
  "MAN",
  "MARUTI SUZUKI",
  "RENAULT",
  "NISSAN",
  "SWARAJ MAZDA",
  "TOYOTA KIRLOSKAR",
  "VE COMMERCIAL",
  "TATA MOTORS",
  "MAHINDRA & MAHINDRA",
  "PIAGGIO",
  "AMW",
  "ISUZU MOTORS",
  "Tvs",
  "BAJAJ TEMPO",
  "TAFE",
  "VOLVO",
  "JCB INDIA LIMITED",
  "FORCE TRAVELLER",
  "HINDUSTAN MOTORS LTD",
  "ESCORTS LTD",
  "Gujarath Tractor Corp LTD.",
  "SCOOTERS INDIA LTD",
  "SML ISUZU",
  "ASHOK LEYLAND LTD",
  "MERCEDES-BENZ INDIA",
  "OMEGA SEIKI EV",
  "MASKTRO MOTORS",
  "FORCE MOTORS LIMTED, A FIRODI TATA",
  "THIRUMALA AGROINDUSTRY",
  "ATUL AUTO LTD",
  "ISUZU MOTORS INDIA PVT LTD",
  "VE Commercials",
  "VSL Industries Ltd",
  "MAHINDRA $ MAHINDRA LIMITED",
  "SML ISUZU LTD",
  "ISUZU",
  "VOLOVO INDIA PVT LTD",
  "FIRE EICHER",
  "BMW",
  "REEP INDUSTRIES PVT LTD",
  "SAME DEVTZ FAHRI PVT LTD",
  "PREMIER",
  "Vikram Auto",
  "John Deer India Pvt LEg",
  "Kirloskar Pneumatic co Itd",
  "DCM TOYOTA LTD",
  "New Holland Tractor",
  "EICHER •",
  "EICHER MOTORS LTD",
  "HMT",
  "BHARAT BENZ",
  "BOBCAT COMPANY",
  "KINETIC GREEN ENERGY",
  "BAJAJ TEMPO LTD",
  "FORCE MOTORS LIMTED,",
  "Bharath Benz",
  "SUNDARAM MOTORS",
  "DAIMMLER 1 COMM VEH P LTD",
  "SWARAJ MAZDA LTD",
  "МАН",
  "MAHINDRA MAHINDRA LIMITED",
  "BAJAJ AUTO",
  "ASHOK LEYLAND",
  "DAIMI FR INDIA COMMERCIAL",
  "AMW",
  "ISUZU MOTORS",
  "Tvs",
  "DAIMLER INDIA COMMERCIAL VEHICLE",
  "BAJAJ TEMPO",
  "TAFE",
  "VOLVO",
  "JCB INDIA LIMITED",
  "FORCE TRAVELLER",
  "HINDUSTAN MOTORS LTD",
  "ESCORTS LTD",
  "Gujarath Tractor Corp LTD.",
  "SCOOTERS INDIA LTD",
  "SML ISUZU",
  "ASHOK LEYLAND LTD",
  "MERCEDES-BENZ INDIA",
  "OMEGA SEIKI EV",
  "MASKTRO MOTORS",
  "FORCE MOTORS LIMTED, A FIRODI TATA",
  "THIRUMALA AGROINDUSTRY",
  "ATUL AUTO LTD",
  "ISUZU MOTORS INDIA PVT LTD",
  "VE Commercials",
  "TATA MOTORS LTD",
  "VSL Industries Ltd",
  "MAHINDRA $ MAHINDRA LIMITED",
  "SML ISUZU LTD",
  "ISUZU",
  "VE Commercials",
  "VOLOVO INDIA PVT LTD",
  "FIRE EICHER",
  "MAHINDRA & MAHINDRA LTD",
  "BMW",
  "REEP INDUSTRIES PVT LTD",
  "Toyota",
  "SAME DEVTZ FAHRI PVT LTD",
  "PREMIER",
  "Vikram Auto",
  "John Deer India Pvt LEg",
  "Kirloskar Pneumatic co Itd",
  "DCM TOYOTA LTD",
  "New Holland Tractor",
  "EICHER •",
  "EICHER MOTORS LTD",
  "HMT",
  "BHARAT BENZ",
  "BOBCAT COMPANY",
  "KINETIC GREEN ENERGY",
  "BAJAJ TEMPO LTD",
  "FORCE MOTORS LIMTED,",
  "Bharath Benz",
  "SUNDARAM MOTORS",
  "DAIMMLER 1 COMM VEH P LTD",
  "SWARAJ MAZDA LTD",
  "МАН",
  "MAHINDRA MAHINDRA LIMITED",
  "BAJAJ AUTO",
  "ASHOK LEYLAND",
  "DAIMI FR INDIA COMMERCIAL",
  "BHARAT BENZ",
  "BOBCAT COMPANY",
  "KINETIC GREEN ENERGY.",
  "BAJAJ TEMPO LTD",
  "FORCE MOTORS LIMTED,",
  "Bharath Benz",
  "SUNDARAM MOTORS",
  "DAIMMLER 1 COMM VEH P LTD",
  "SWARAJ MAZDA LTD",
  "МАН",
  "MAHINDRA MAHINDRA LIMITED",
  "BAJAJ AUTO",
  "ASHOK LEYLAND",
  "DAIMLER INDIA COMMERCIAL",
  "VE COMMERICAL VEHICLE LTD",
];

export const companies = [
  ...tempCompanies.map((company) => ({
    [company]: company,
  })),
];

export const modalTypes = {
  "DAIMLER INDIA COMMERCIAL VEHICLE": [
    "Bharath Benz 4928 TT 6X4",
    "Bharath Benz 4928 TT 6X4",
  ],
  "ASHOK LEYLAND": [
    "Ashok Leyland Taurus 2516",
    "ALPSV 4/38",
    "Ashok Leyland Comet 1611",
    "Ashok Leyland DOST",
    "Ashok Leyland ALPSV 4/161",
    "ALFSV3/46-LYNX",
    "Ashok Leyland PARTNER-c3",
    "Ashok Leyland Lynx",
    "Ashok Leyland Ecomet 1012",
    "Ashok Leyland 1212",
    "Ashok Leyland ALPSV 4/186",
    "Ashok Leyland 1214 SMART",
    "Ashok Leyland Viking ALPSV 4/247",
    "Ashok leyland ALPSV 4/88",
    "Ashok Leyland Tusker Super 2214",
    "Ashok Leyland ALPSV Viking 4/83",
    "Ashok Leyland ECOMET 1112",
    "Ashok Leyland CT 1613",
    "Ashok Leyland Ecomet 912",
    "Ashok Leyland Ecomet 912",
    "Ashok Leyland 3718",
    "Ashok Leyland U 2523",
    "Ashok Leyland Viking Bus",
    "Ashok Leyland 3516 Trailer",
    "Ashok Leyland 3517 Trailer",
    "Ashok Leyland 3518 Tanker",
    "Ashok Leyland 3518 Bulker",
    "Ashok Leyland U-3123 T AL 2518 Tipper",
    "Ashok Leyland ALPSV 4/89:",
    "Ashok Leyland 1214 CONTAINER",
    "Ashok Leyland 3118",
    "AL 1611 CONTAINER",
    "Ashok Leyland BOSS 1212",
    "Ashok Leyland 2513",
    "Ashok Leyland BOSS 1212 LE",
    "Ashok Leyland COMMET TIPPER 1616XL",
    "Ashok Leyland 2516 Tipper",
    "Ashok Leyland TUSKER TURBO TRACTOR 3516",
    "Ashok Leyland 1613 Tipper",
    "Ashok Leyland ECOMET 1109",
    "Ashok Leyland ALPEV 1/38",
    "Ashok Leyland BOSS 1412 CONTAINER",
    "Ashok Leyland BOSS 1115 CONTAINER",
    "AL 4123 Tanker",
    "Ashok Leyland STILE",
    "Ashok Leyland GA 1920/43 H CO",
    "Ashok Leyland Boss 1413",
    "Ashok Leyland GURU 1111",
    "Ashok Leyland 4923TT BULKER",
    "AL 1618 lipper",
    "Ashok Leyland 4923 Trailer",
    "Ashok Leyland UE5525/39 TTCC",
    "Ashok Leyland PARTNER MLS",
    "AL 3516 Bulker:",
    "Ashok Leyland 2513",
    "Ashok Leyland 3518",
    "Ashok Leyland PA 1215/52 HCC",
    "Ashok Leyland ALPSV 4/56",
    "Ashok Leyland 4921 WB",
    "Ashok Leyland 709",
    "Ashok Leyland Cargo 709",
    "Ashok Leyland VK 1811",
    "Ashok Leyland UE5525-39 TTCC",
    "Ashok Leyland 4218",
    "Ashok Leyland 4018",
    "Ashok Leyland U 2512",
    "Ashok Leyland 2514",
    "AL 4023 Container",
    "ECOMET 1015",
    "ALCO 3/16-3600MM",
    "ALPSV 1/40",
    "AL 3516",
    "AL 1918",
    "PARTNER",
    "AL STAG 3/26",
    "AL STAG 3/26",
    "3516 - canter - c3",
    "CARGO 100.12",
    "ALPSV",
    "BOSS 913",
    "GF3520/66HCO",
    "MINI BUS",
    "SCHOOL BUS",
    "ASHOK LEYLAND TAURUS MK It 150WB",
    "4018-C4",
    "SS1008",
    "CA1615/52 H FBL 1615",
    "EA19020/43H",
    "Dost ( New Vehicle)",
    "1612L Goods Chasiss Cabin N3",
    "Ashok Leyland 3611 - IL",
    "207D| EX4SPCR10 CCD1 L3150 W",
    "1616 XL Tipper",
    "Ashok Leyland 1612 Tanker",
    "Ashok Leyland 2513",
    "Ashok Leyland 1612 Tanker",
    "Ashok Leyland U2523 Tipper",
    "CHEOTOH ALPS 1/30",
    "AL 4921/4923 Cement Trailer",
    "AL 3118 Bulker 12Wheel",
    "ASHOK LEYLAND CRUSHER COMET",
    "CRUSHER 2516",
    "CRUSHER 2516",
    "Ashok Leyland 1611/2-142 WB",
    "2214/19 180WB TUSKER 6X2",
    "AL 1618 LPG Tanker",
    "GURU 1010 E4",
    "Ashok leyland 3121 205 WB",
    "Ashok Leyland 3516 Trailer",
    "AL 1613",
    "Ashok Leyland Boss 1113",
    "Ashok Leyland 4023",
    "AL 2214 Tusker Super Tanker",
    "AL 1616 Tanker",
    "GM4220/66 HCO",
    "Ashok Leyland 2513",
    "AL TF1812 Bus",
    "AL ECOMET 1214/42 E4",
    "AL CA1415/39",
    "AL 4921 CEMENT TRAILER",
    "AL 3516 BULKER AL 3516 BULKER",
    "Ashok Leyland Comet 912",
    "Ecomet 1212 E4/1",
    "AL 4/157 Bus",
    "Ashok Leyland 4018 Cement Trailer",
    "ALPSV 3/41",
    "Ashok Leyland DOST - 50mm",
    "Ashok Leyland ALPSV 4/188",
    "AL TUSKER SUPER 2214",
    "AL 3116",
    "AL 3118",
    "AL 3718 Trailer",
    "AL 4/157 MiniBus",
    "AL CO 1510",
    "Ashok Leyland 2513",
    "AL 4/157 MiniBus",
    "AL CO 1510",
    "AL 2516 Tusker Super",
    "AL 1616 222 WB",
    "AL 2614 Trailer",
    "AL 2516 Tanker",
    "AL 1614 Tipper",
    "AL Boss 912",
    "AL 4921 Bulker",
    "ALPSV 3/4 Bus",
    "AL 2818",
    "AL 2516 TANKER 10Wheel",
    "AL 2518 Tanker",
    "ALH 1/9 18 Wheel",
    "AL 2516 30FT Container",
    "AL COMET 1510",
    "AL CARGO 909",
    "HMV HEAVY GOODS CARRIER",
    "AL 2518 Concrete Mixture",
    "AL CA1015/39 Tanker",
    "Ashok Leyland 2513",
    "cnzusoos lanker",
    "AL 1618 CONTAINER (27FT)",
    "ALPSV 4/38 - MiniBus",
    "AL 3116 12 Wheel",
    "AL Tipper 6 Wheel",
    "ALCO 3/1",
    "ECOMET 1412",
    "AL 1512 Cargo",
    "AL 2518",
    "AL 3116 12Wheel Tanker",
    "AL 3718 Tanker 14Wheel",
    "GP4825/66 H CO",
    "2516T 198WB TUSKER SUPER 6X2",
    "AL VK1611 Bus",
    "AL 2818 Tanker",
    "AL Boss 1112",
    "AL 4188 210(WB)",
    "AL 4/157",
    "AL 4019 Cement Trailer",
    "Ashok Leyland 2513",
    "AL 4019 Cement Trailer",
    "AL LS1310 Bus",
    "AL 4019 Trailer (22 FT)",
    "DOST - New Vehicle",
    "AL COMET 415",
    "AL 3718 BS IV",
    "AL 4/19",
    "AL Boss 1412",
    "AL HMV BUS",
    "AL CARGO 1312",
    "AL TF1812 BUS AL 3611 Bulker",
    "AL 2214 Container (22 FT)",
    "AL 4023 Trailer",
    "AL 1616 IL",
    "AL 1618 Tanker",
    "AL Boss 1113 Container",
    "AL 4/38 Tanker",
    "AL 1616 Container (32FT)",
    "AL ALPSV 3/106",
    "Ashok Leyland 2513",
    "AL ALPSV 3/106",
    "AL Ecomet 1110",
    "AL 1616 Container",
    "ALPSV 3/106 BSIII",
    "AL MITR LES",
    "AL 1613 Container (20FT)",
    "AL 4123",
    "AL COMET 910",
    "AL 139.3D4R Bus",
    "BOSS 1213",
    "AL U2518 Tipper",
    "AL Boss 1415",
    "Tata Lop 7.5 T Star Bus Ultra",
    "AL FV2518 Trailer",
    "AL 4018",
    "AL 3520/63",
    "AL 1612 Container (18FT)",
    "AL Educational Institution Vehicle",
    "AL 3118 Tanker",
    "AL CT1613H",
    "AL CT1613H",
    "AL 415/5 Trailer",
    "AL 1256",
    "AL 2214 Tusker",
    "AL UE2825/39 TIPPER",
    "AL 1612",
    "AL 3118 IL Tanker (27FT)",
    "AL 3123 Tipper 12W",
    "AL 4825 16W",
    "AL LS1308 Bus",
    "AL 4188",
    "AL 3718 Bulker",
    "AL 1215 Container",
    "AL 1/38 Container (32FT)",
    "AL 2516 Container",
    "AL 1618",
    "AL 1616 Closed Body",
    "1214 ECOMET",
    "Ashok Leyland 2513",
    "AL 1256",
    "AL 2214 Tusker",
    "AL UE2825/39 TIPPER",
    "AL 1612",
    "AL 3118 IL Tanker (27FT)",
    "AL 3123 Tipper 12W",
    "AL 4825 16W",
    "AL LS1308 Bus",
    "AL 4188",
    "AL 3718 Bulker",
    "AL 1215 Container",
    "AL 1/38 Container (32FT)",
    "AL 2518 Container (24FT)",
    "AL 1616 Fire Service Tanker",
    "AL 2516 Container*",
    "AL 1618",
    "AL 1616 Closed Body",
    "1214 ECOMET",
    "GA4020/34 TT CO",
    "Ashok Leyland 2513",
    "Ashok Leyland 3518 Trailer",
    "Ashok Leyland 4019 Tanker",
    "Ashok Leyland 4019 Trailer",
    "Ashok Leyland 4019 Bulker",
    "Ashok Leyland 4018 Bulker",
    "Ashok Leyland 3116",
    "Ashok Leyland ALPSV 4/28",
    "AL 1616 Container (27FT)",
    "AL 2518 Container (24FT)",
    "AL 1616 Fire Service Tanker",
  ],
  "ASIA MOTORS": ["AMW 2518", "AMW 2518", "ASIA 2523", "AMW 2516"],
  BAJAJ: [
    "Bajaj Tempo Traveller Cruisier",
    "Bajaj Tempo Traveller Cruisier",
    "Bajaj Tempo",
    "Bajaj Auto",
    "Bajaj Auto - 50mm",
    "Bajaj Auto - Yellow",
    "Bajaj Matador 307",
    "Bajaj Maxima Load Auto",
    "Bajaj Minidoor",
    "Bajaj Maxima Auto",
  ],
  "FORCE MOTORS": [
    "Force Traveller",
    "Force Traveller",
    "Tempo Traveller",
    "TRUMP 40 PICKUP",
    "Minidor",
    "MINIDOR - 50mm",
    "TEMPO EXCELA",
    "Force Cruiser",
    "Trax",
    "Force Citiline",
  ],
  FORD: ["Ford Figo", "Ford Figo Aspire", "Ford Figo - 50mm"],
  "GENERAL MOTORS": [
    "Cheverolet Tavera - 50mm",
    "Cheverolet Tavera - 50mm",
    "Cheverolet Enjoy",
    "Chevrolet Beat",
    "Chevrolet Sail",
    "Cheverolet Tavera",
    "Cheverolet Enjoy - 50mm",
  ],
  "HINDUSTAN MOTORS": ["Ambassador - 50mm"],
  HONDA: [
    "Honda Amaze",
    "Honda Amaze",
    "Honda City",
    "Honda Mobilio",
    "Honda Amaze - 50mm",
  ],
  HYUNDAI: [
    "Hyundai Xcent - 50mm",
    "Hyundai Xcent - 50mm",
    "Hyundai SANTRO",
    "Hyundai Grand",
    "Hyundai 110",
    "Hyundai EON",
    "Hyundai Xcent",
    "Hyundai i10 - 50mm",
  ],
  MAN: [
    "MAN 25.250 TRUCK",
    "MAN CLA Tanker",
    "MAN CLA Trailer",
    "MAN CLA Bulker",
    "MAN CLA 16.220",
    "MAN CLÁ 49.290",
    "MAN CLA 25.80",
    "MAN CLA 40.280",
    "CLA 25.280 Concrete Mixure",
    "CLA 25.280",
    "MAN 40.220",
    "MAN 25.180 Tanker",
    "MAN 25.250 TRUCK",
  ],
  "MARUTI SUZUKI": [
    "Maruti Suzuki Wagon R",
    "Maruti Suzuki Wagon R",
    "-Maruti Suzuki Ritz",
    "Maruti Celerio",
    "Maruti Suzuki Alto K10",
    "Maruti Gypsy",
    "Maruti Suzuki Esteem",
    "Maruti Versa",
    "Maruti Omni",
    "Maruti Swift",
    "Maruti Suzuki EECO",
    "Swift Dzire Tour",
    "Maruti Suzuki Ertiga",
    "MARUTI SUPER CARRY",
    "Swift Dzire - 50mm",
    "MARUTI SUPER CARRY - 50mm",
    "Maruti Omni - 50mm",
    "Maruti Ritz - 50mm",
    "Maruti Super Carry - 50mm Maruti Suzuki EECO - 50mm",
    "Maruti Celerio - 50mm",
  ],
  RENAULT: [
    "Renault Lodgy - 50mm",
    "Renault Lodgy - 50mm",
    "Renault Kwid",
    "RENAULT LODGY",
  ],
  NISSAN: [
    "Nissan Sunny",
    "Nissan Sunny",
    "Nissan Micra",
    "Nissan Datsun GO",
    "ALLWYN",
    "Nissan Sunmy -50mm",
    "Nissa",
  ],
  "SWARAJ MAZDA": [
    "Swaraj Mazda ZT 54",
    "Swaraj Mazda Super",
    "SML Samrat",
    "SML SARTAJ 5252",
    "SML ISUZU WV 26S T3500",
    "Swaraj Mazda T 3500",
    "SML SAMRAT TURBO",
    "Swaraj Mazda T3500 Bus",
    "SML MAXI CAB / Omni Bus",
    "Swaraj Mazda OMNI BUS",
    "SWARAJ MAZDA WT48E",
    "SML SARTAJ WV 26S  Bus",
    "SWARAJ MAZDA SUPER",
    "Swaraj Mazda SCHOOL BUS",
    "SML 3500 Tourist Van",
    "SML SARTAJ GS",
    "CARGO BOX",
    "SML - 25 Seater PSV",
    "Swaraj Mazda G5",
    "SML T3500 Tipper",
    "SML Cosmo",
    "Swaraj Mazda T3500 MiniBus",
    "Swaraj Mazda ZT 54 Bus",
    "SML Prestige",
    "SML Samrat 4240 container (20FT)",
    "SML Prestige Van",
    "SML Single Stretcher Ambulance",
    "SML S7 3335 Bus",
    "SML T3500",
    "LMW 17Ft",
    "LMW 17Ft",
    "SML WV 27U Ambulance",
    "SML SARTAJ School Van",
    "SML S7 5100 Bus 53 seater",
    "SML Prestige 3940 32S Van",
    "SML 3500 Tanker",
    "SWARAJ MAZDA WT50 Van",
    "SML Supreme 4760 Bus",
    "SWARAJ MAZDA 3500",
  ],
  "TOYOTA KIRLOSKAR": [
    "Toyota Etios",
    "Toyota Etios LIVA",
    "Toyota Innova",
    "TOYOTA INNOVA - 50mm",
    "Toyota Etios - 50mm",
  ],
  "VE COMMERCIAL": [
    "Eicher 10.75",
    "Eicher 10.50",
    "Eicher 30.25",
    "Eicher 20.15",
    "Eicher 20.16",
    "Eicher 11.10",
    "Eicher 10.59 / Pro 1059",
    "Eicher 10.90",
    "Eicher 10.95",
    "Eicher 10.80",
    "Eicher 11.12",
    "Eicher 10.70",
    "Eicher Pro  11.10 container (20FT)",
    "Eicher Terra 16",
    "Eicher Mitsubishi Canter",
    "Eicher 10.60",
    "EICHER PRO 5016",
    "EICHER 10.50 D BUS",
    "EICHER LGV (OLD)",
    "Eicher MAXI CAB",
    "Eicher Pro 1049",
    "EICHER 10.50 C BUS",
    "MOTOR D VAN 150 HP",
    "Eicher PRO 6025 T G CAB TIPPER 16 CUM",
    "EICHER 10.75 BUS",
    "EICHER PRO 3016",
    "EICHER 10.70",
    "EICHER PRO 6031 P CWC",
    "EICHER 242 PREMIUM",
    "EICHER PRO",
    "EICHER 10.90 BUS",
    "EICHER BUS",
    "EICHER 35.31",
    "EICHER PRO 1095",
    "Tractor",
    "EICHER PRO 5028",
    "EICHER PRO 2095XPT",
    "EICHER pro5035 D",
    "EICHER -11.10 PRO(LBC -24 FEET)",
    "EICHER -11.50(14- FEET)",
    "EICHER 10.90 (17 FEET)",
    "EICHER -10.50 (3 IN ALL)",
    "EICHER -10.90(CAB & FSD)",
    "EICHER CRUISER",
    "EICHER 11.12 G DSD BS III",
    "Eicher Pro 1055C",
    "Eicher Pro 5019",
    "EICHER 10.50 E HSD",
    "Eicher Pro 2049",
    "Eicher Pro 1114XP",
    "Eicher 10.50 Van",
    "Eicher 5016 Tipper",
    "Eicher 20.15 Bus",
    "Eicher Pro 10.50E",
    "Eicher 10.70 Bus",
    "Eicher Pro 1080XPT",
    "EICHER -20.50D BUS",
    "Eicher 50.16 Container",
    "Eicher Pro 8049",
    "Eicher Pro 5040 Trailer",
    "EICHER 10.55 C BSIII",
    "Eicher 10.50 Container",
    "Eicher 30.15",
    "Eicher Pro 6048",
    "Eicher 10.50 27S StarBus",
    "Eicher Pro 3009 Bus",
    "Eicher PRO 2080XP F HSD",
    "Eicher 3350",
    "Eicher Pro21.10",
    "Eicher Canter LCV",
    "Eicher Terra 25G",
    "Eicher pro 6025 s cowl",
    "Eicher Pro 1110",
    "Eicher 10.59 LGV",
    "PRO 6037S",
    "Eicher Pro 3012",
    "Eicher 10.75 Bus",
    "Eicher Pro 1095XP",
    "EICHER 10.90 Container (20 FT)",
    "Eicher Pro 2110 Container",
    "Eicher Pro 2095 XP",
    "Eicher 11.10 LCV",
    "EICHER Pro 1090 15 Feet Container",
    "EICHER  RHD E CAB AND HSD",
    "Eicher Pro 6041",
    "PRO 6037S SLEEPER BS3",
    "Eicher 20.16 Tanker",
    "Eicher 20.15 Bus",
    "EICHER 20 16RHD R FACE COWL",
    "Eicher Pro 1095X",
    "EICHER  PRO 1110H CAB HSD BSIII",
  ],
  "TATA MOTORS": [
    "TATA Magic",
    "TATA ACE",
    "TATA Indica",
    "TATA Winger",
    "TATA 4018",
    "TATA 207",
    "TATA Indigo",
    "TATA  709 STARBUS",
    "TATA 909",
    "TATA  1615",
    "TATA Magic Iris",
    "TATA 3516",
    "TATA 2515",
    "TATA 1210 Tanker",
    "TATA 1613",
    "TATA  1616",
    "TATA Marcopolo STARBUS",
    "TATA Marcopolo STARBUS",
    "TATA 709 - C3",
    "TATA Indigo Manza",
    "TATA Indica - 50mm",
    "TATA  2515 Trailer",
    "TATA 410",
    "TATA 2518",
    "TATA  1109",
    "TATA  3118",
    "TATA  407",
    "TATA 1510",
    "TATA 3718",
    "TATA 712",
    "TATA 712 STAR BUS",
    "TATA Bolt",
    "TATA Cityride Bus",
    "TATA LPT 1512",
    "TATA LPK 1612",
    "TATA Sumo Gold",
    "TATA SUMO VICTA",
    "TATA Super Ace",
    "TATA Tiago",
    "TATA Ultra 912",
    "TATA Ultra 1012",
    "TATA Xenon Pick Up",
    "TATA Zest",
    "Tata  3516 Tanker",
    "TATA 3516 Trailer",
    "TATA 3516 Bulker",
    "TATA 3518 Tanker",
    "TATA 3518 Trailer",
    "TATA 3518 Bulker",
    "TATA 4018 Tanker",
    "TATA  4018 Trailer",
    "TATA 218",
    "TATA 407",
    "TATA Spacio Gold",
    "TATA  2516",
    "TATA SFC 407/31",
    "TATA LPT 1412",
    "TATA LPT 1010 CR X /38WB BSIV",
    "TATA 912",
    "TATA PRIMA LX4923S 6 X 4",
    "TATA LPO 1515 BUS",
    "TATA LPT 1112",
    "TATA LPT 1212",
    "Prima LX 2525",
    "TATA  INTRA",
    "TATA 4225",
    "LPK 1618/36",
    "Tata 709",
    "LPC 4923",
    "1109 BUS",
    "TATA SIGNA 5523",
    "TATA 3118 Tipper",
    "TATA 1918",
    "SFC 410/31 EX",
    "LPT 4223",
    "ULTRA 1518.T",
    "Tata LP 1512 TC/59",
    "LPK 2518 TIPPER",
    "LPK 1613 697TC - Short",
    "TATA LPT 1010 CRX/38WB BSIV",
    "TATA 1613 HEAVY GOODS VEHICLE",
    "TATA ACE ZIP BSIII",
    " TATA CRUISER 912",
    "TATA SIGNA 4923.S CRE BSIV",
    "TATA LPS 4923",
    "Tata 1613 Tanker",
    "TATA 407 Tourist Van",
    "TATA LPT 3118",
    "Tata LPT 1618",
    "LPT 909 Container",
    "TATA SA 1212 T TC BS- IV  4X4",
    "TATA SA 1212",
    "LPT 2416",
    "TATA LPK 912EX/27 BSIV",
    "TATA ACE - 50mm",
    "TATA Winger - 50mm",
    "LPK 1616",
    "Tata SUMO - 50mm",
    "Tata 407/27 City Ride School Bus",
    "Tata Intra V20 - 50mm",
    "Tata Prima LX3125 Tipper",
    "Tata Ultra T7",
    "Tata Signa 2823",
    "Tata 3118 Bulker",
    "Tata 3118 Tanker",
    "LPK 2523",
    "Tata Zest - 50mm",
    "MAGIC MAXI CAB",
    "Tata Bolt - 50mm",
    "Tata LPT 1913",
    "Tata 609",
    "Tata LT410 StarBus",
    "LPT  1109 Container (18FT)",
    "LPK 1212 Tipper",
    "SFC 909 BUS",
    "TATA DP 1313 TO 55",
    "TATA DP 1313 TO 55",
    "ULTRA 1014/39WB",
    "Tata Super Ace Mint",
    "TATA 207 - 50mm",
    "LPT 1109",
    "TATA 1210",
    "TATA Ace Container",
    "Tata 3015 cement trailer",
    "LPK 1613 - Long",
    "Tata LPT 407EX2/38 BSIV",
    "Tata LPT 909 Tanker",
    "Tata 712 Bus",
    "Tata Ultra 1012/33",
    "LPT 1615 Container",
    "TATA Indigo - 50mm",
    "TATA LPO1512 Bus",
    "LPT 1212 Container",
    "Tata ARIA - 50mm",
    "Tata lpt-810",
    "Tata Ultra 1518",
    "TATA LPT 3723 TC",
    "TATA LPT 3712",
    "TATA 2518 Concrete Mixture",
    "TATA Xenon Pick Up - 50mm",
    "TATA Signa 4223",
    "LPT 1109 - LCV",
    "TATA LPT 3518 Tipper",
    "Tata Ace Mega XL",
    "Tata LPT 912",
    "Tata  Lop 7.5 T Star Bus Ultra",
    "TATA LP 912 Bus",
    "TATA 2518 Tanker",
    "TATA PRIMA 2525 Tipper",
    "Lpo 1613 school Bus",
    "TATA 2818 Container (18FT)",
    "LPK 1616 Tipper",
    "Tata LP 309/38 Bus",
    "Tata Venture",
    "3 CUM TIPPER",
    "Tata Maxi Cab",
    "Tata Signa 4223",
    "TATA INTRA V30 BS-VI",
    "Tatra-IND T815",
    "PRIMA 3525",
    "TATA LPS 4018",
    "TATA LPS 4018",
    "TATA LPS 4018",
    "TATA MARCOPOLO LP810 FBV",
  ],
  "MAHINDRA & MAHINDRA": [
    "Mahindra Bolero",
    "Mahindra TUV 300",
    "Mahindra Voyger",
    "Mahindra  Marshall 2000",
    "Mahindra Bolero Pick-up",
    "Mahindra Maxx Maxi Truck",
    "Mahindra Loadking",
    "Mahindra Tourister",
    "Mahindra Bolero Maxi truck",
    "Mahindra DI3200",
    "Mahindra Logan",
    "Mahindra KUV 100",
    "Mahindra Maxi Cab",
    "Mahindra Navistar",
    "Mahindra Maxximo Mini VAN",
    "Mahindra Scorpio",
    "Mahindra Torro 25",
    "Mahindra Supro Mini Van",
    "Mahindra Truxo",
    "Mahindra Traco",
    "Mahindra Xylo",
    "Mahindra Verito",
    "Mahindra Bolero  camper",
    "Mahindra XUV500",
    "Mahindra Loadking Tipper",
    "Mahindra Genio",
    "Mahindra ALFA",
    "Mahindra SUPRO MAXI  TRUCK",
    "Mahindra TRACTOR",
    "Mahindra TRACTOR WITH TRAILER",
    "MAHINDRA SINGLE CAB",
    "Mahindra TRACTOR WITH SHORT TRAILER",
    "Mahindra BLAZO",
    "MAHINDRA CHAMPION CONTAINER",
    "Mahindra MARAZZO",
    "Mahindra Champion",
    "MAHINDRA LOADKING-C3",
    "MN 25 TANKAR",
    "M BLAZO",
    "MTB T25 BS4",
    "Mahindra MN40X",
    "Mahindra 575 Tractor",
    "Mahindra Jeep - Load",
    "Mahindra MN31 cement body",
    "Mahindra Bolero Pick-up - 50mm",
    "Mahindra Jeeto - 50mm",
    "Mahindra Xylo - 50mm",
    "Mahindra ALFA - 50mm",
    "Mahindra Maxximo",
    "Mahindra Maxximo - 50mm",
    "Mahindra Bolero  camper - 50mm",
    "Bolero ( New Vehicle)",
    "Mahindra EJ470",
    "BLAZO TRAILER",
    "Mahindra ALFA - Yellow",
    "MTB T40 Bus",
    "Mahindra Jeeto",
    "Mahindra Champion - 20mm",
    "Mahindra Blanzo 45.5",
    "Mahindra MARAZZO - 50mm",
    "MTB T20 Maxi Cab",
    "Mahindra Bolero Maxi truck - 50mm",
    "Mahindra ALFA - Passenger",
    "Mahindra Furio 12 / 14",
    "Mahindra Alwyn Cab",
    "Mahindra Jeeto - New Vehicle",
    "Mahindra Ambulance",
    "Cosmo Tourister",
    "COMMANDER 750",
    "Mahindra Maxximo Mini VAN - 50mm",
    "Mahindra 475-D1 Tractor",
    "Mahindra LGV",
    "Mahindra cosmo",
    "Bolero City Pickup Container",
    "Mahindra Bolero Power",
    "Mahindra  Blazo 49HL",
    "Mahindra Imperio",
    "Mahindra Navistar MN 25 Tanker",
    "Mahindra Gio",
    "Mahidra Tourister 25 seat",
    "Mahindra open body van",
    "Mahindra Verito - 50mm",
    "Maxximo Load Container Auto",
    "Mahindra Supro Mini Van",
    "Mahindra Truxo Container - 28FT",
    "Mahindra CabKing 3150",
    "Mahindra Jeep",
    "Mahindra Torro 25 Tipper",
    "Mahindra Maxx",
    "MN Tourister 4800",
    "MAHINDRA XYLO D4VDICW",
    "MAHINDRA XYLO D4VDICW",
  ],
  PIAGGIO: [
    "Ape Auto",
    "PIAGGIO PORTER 600",
    "APE CARGO",
    "APE XTRA LD",
    "Ape Auto - 50mm",
    "Ape Cargo - 50mm",
    "Ape Auto - Yellow",
    "Ape Auto - 3Yellow",
    "PIAGGIO PORTER 600 - 50mm",
    "APE XTRA LD - 50mm",
    "Ape 4 wheel Auto",
  ],
  AMW: [
    "AMW Tanker",
    "AMW Trailer",
    "AMW Bulker",
    "AMW TRUCK 2518",
    "AMW 2523 Tipper",
    "AMW 2528 Tipper",
    "AMW 3116",
  ],
  "ISUZU MOTORS": ["Isuzu D-max Flat Deck"],
  Tvs: ["TVS Auto", "Tvs Auto - Yellow"],
  "BAJAJ TEMPO": [
    "BHARAT BENZ 1214R",
    "BHARATBENZ 2523",
    "BHARATBENZ 914R",
    "BHARATH BENZ 1617 TANKER",
    "BHARATBENZ 2528",
    "BharatBenz BUS",
    "BHARAT BENZ 14 R BS IV 10",
    "BHARATBENZ 2523 6X2 BSIV",
    "Bharat Benz 3723R",
    "BHARAT BENZ 1617R",
    "BHARAT BENZ 3723",
    "Bharath Benz 1014R BSIV 3",
    "BharatBenz 3123R container",
    "Bharatbenz 1015R BSVI",
    "BHARATBENZ 1923C",
    "BharatBenz 2823",
    "BharatBenz 1623C Tipper",
    "BharatBenz 4228R",
    "BharatBenz 5528TT",
    "BharatBenz 2523 Tanker",
    "BharatBenz 1215R",
    "BharatBenz 2823 Tanker",
    "BharatBenz 25.23",
    "BharatBenz 4023 LPG Tanker",
    "BharatBenz 4023 Trailer",
    "BharatBenz 3128C",
    "BharatBenz 2523 Container",
    "BharatBenz 1617 container (32FT)",
    "BharatBenz 3123R",
    "BharatBenz 1214 Container (20FT)",
    "BharatBenz 2523 Tipper",
    "BharatBenz 1617 Container",
    "BharatBenz 1217 Tipper",
    "BharatBenz 3123",
    "BharatBenz 1014R Container",
    "BharatBenz 3123 Tanker",
    "BharatBenz 1214 Road Sweeper",
    "BharatBenz 4928 Bulker",
    "BharatBenz 1214 Tanker",
  ],
  TAFE: [
    "MF TAFE TRACTOR WITH TRAILER",
    "TAFE MM TRACKTOR",
    "Tafe Tractor (Trailer Only)",
  ],
  VOLVO: ["VOLVO 9400 B8R", "VOLVO", "Volvo B7R", "Volvo Fire Service"],
  "JCB INDIA LIMITED": ["JCB"],
  "FORCE TRAVELLER": ["FORCE TRUMP", "TRAX CRUISER"],
  "HINDUSTAN MOTORS LTD": ["RTV DSL"],
  "ESCORTS LTD": ["POWERTRAR 434 TRACTOR", "Escorts 340 Tractor"],
  "Gujarath Tractor Corp LTD.": ["2 MV Tractor"],
  "SCOOTERS INDIA LTD": ["Vikram 750cc Auto"],
  "SML ISUZU": ["SAMRAT 2815"],
  "ASHOK LEYLAND LTD": [
    "3120 8 2 GOODS CHASSIS WCWW",
    "AL 3518",
    "AL 4218",
    "AL GF 3520/66HCO",
    "AL GF 4220/66HCO",
    "FV4923",
    "ASHOK LEYKAND DOST",
    "HGV 3118XL TANKER",
    "HAULAGE CHASSIS",
    "1614 .1 TIPPER",
    "3116IL GOODS CHASI W COWLWWB",
    "2516t 198 wb tusker sup",
    "VK1611.0D4R",
    "ALPSV 4/170",
    "TAURUS 2516/2",
    "AL 3518 TANKAR",
    "SS1008 .1D4RB(39+",
    "SS1008 .1D4RB(39+) SHCOOL BUS",
    "AL GB2820",
    "AL 4118",
    "2214",
    "3015",
    "E 2820 6X4 CONCRETE MIXER",
    "AL 1611",
    "LT1300.3D4RB/C",
    "LPO 1616 TC BUS BS 2",
    "HEAVY GOODS",
    "ALPSV 4/186",
    "AL BOSS",
    "1616-185TUSKER SUPER",
    "GURU 1111 GOOD CWC N2 BS IV",
    "1612 170 5WB G",
    "GURU 1111 GOOD CWC N2 BS IV",
    "1612 170 5WB G",
    "AL CT 1613H/1",
    "2518T IL TIP CHAS CABIN TIP B",
    "AL BEARER ALB 1/1 HAULOGO",
    "DOST LS BS III",
    "HIPPO TRUALAR",
    "ASHOK LEYKAND 3118 BSIV",
    "3718 T BSIV TIP CWC WO L",
    "DOST LS BS III",
    "2214/2S 198 (CWB) GOODS CHAS",
    "AL 3116 DIESEL TANKAR",
    "COMET SUPER",
    "Cheetah ALPSV 1/30",
    "3118IL AL",
    "3118IL AL",
    "3118IL AL",
    "GURU 1111 GOOD CWC N2 BSIV",
    "GURU 1111 GOOD CWC N2 BSIV",
    "GURU 1111 GOOD CWC N2 BSIV",
    "TUSKER SUPER",
    "AL4923 BULKER",
    "AL 4923 BULKER",
    "1616 L4 GOOD N3 BSIII",
    "FV.4923.BSIII",
    "CA1015/28T TIP 2850",
    "1612",
    "ASHOK LEYKAND 3118 BSIV",
    "CS 42/166",
    "UJ3525/52T TIP 5250",
    "2516 IL 193 WB",
    "1616 XL/3 BSIII",
    "ASHOK LEYLAND LTD 3118IL BSIII",
    "TUSKER SUPER",
    "2214/2S 198 (CWB) GOODS CHAS",
    "VK1811.0D4R",
    "LT 1309 .3D4R",
    "AL3 116IL",
    "OTHERS",
    "DOST RLS BSIV",
    "PARTNER LES",
  ],
  "MERCEDES-BENZ INDIA": ["E220 D"],
  "OMEGA SEIKI EV": ["Rage plus"],
  "MASKTRO MOTORS": ["ARJUN 500 SHARE AUTO"],
  "FORCE MOTORS LIMTED, A FIRODI TATA": [
    "TRAVELLER 11 AMBULANCE",
    "TRAVELLER T2 SCHOOL  BUS",
    "TRAVELLER T1 SCHOOL  BUS",
  ],
  "THIRUMALA AGROINDUSTRY": ["TEMPO TRAVELLER"],
  "ATUL AUTO LTD": ["Atul Auto - 50mm"],
  "ISUZU MOTORS INDIA PVT LTD": ["ISUZU D MAX CAB"],
  "VE Commercials": ["Eicher Pro 3009 H BS IV"],
  "VSL Industries Ltd": ["VSL Dot & Dot Mini"],
  "MAHINDRA $ MAHINDRA LIMITED": [
    "BOLERO CITY PIX UP 14 PS",
    "BOLERO CITY PIX UP 14 PS",
    "BOLERO CITY PIX UP 1.4 PS",
    "BOLERO CITY PIX UP 1.25T BSIV",
    "BOLERO PICK UP FB PS MH 2WD BS3",
    "BMT PLUS PS127",
    "SUPRO TRUCK VX",
    "BOLERO MAXI TRUCK",
  ],
  "SML ISUZU LTD": [
    "EXECUTIVE TC 111",
    "SAMRAT 4760 CONTAINER",
    "BSIV ZT 54E BSIV LWO",
    "WV26SOTNSCHOOL BUS 21 SEAT",
    "SARTAJGSHG72STEELHIGHDECKSHD12",
    "S7 SCHOOL BUS BS IV",
    "T3500 WT50L WB DELUXE",
    "PRESTIGE 3940 LWB BUS STD",
  ],
  ISUZU: ["EXCECUTIVE TC III WV"],
  "VOLOVO INDIA PVT LTD": ["OPEN PLW"],
  "FIRE EICHER": ["FIRETENDER"],
  BMW: ["BMW 520D", "BMW 730LD"],
  "REEP INDUSTRIES PVT LTD": ["3WT (Electric)"],
  Toyota: ["Toyota Qualis"],
  "SAME DEVTZ FAHRI PVT LTD": ["SAME603"],
  PREMIER: ["Premier Ferguson HMV", "Premier Tipper"],
  "Vikram Auto": ["Vikram auto"],
  "John Deer India Pvt LEg": ["John Deer 5045 V2"],
  "Kirloskar Pneumatic co Itd": ["Road Ropar semi Trailer"],
  "DCM TOYOTA LTD": ["LGV", "DCM TOYOTA MGV"],
  "New Holland Tractor": ["3600 Tractor"],
  "EICHER •": ["Eicher 6035 p cwc tankar"],
  "EICHER MOTORS LTD": [
    "EICHER TERRA 16",
    "Eicher Pro 1059",
    "10.75 H BUS NS BSIII",
    "TONGA DIESEL 24 SOFT TOP",
  ],
  HMT: ["HMT 212 TRACTOR"],
  "BHARAT BENZ": ["BHARAT BENZ 2523C BS 4"],
  "BOBCAT COMPANY": ["AUTO RICKSHAW "],
  "KINETIC GREEN ENERGY": ["JUMBO PICKUP", "JUMBO PICK UP"],
  "BAJAJ TEMPO LTD": ["Force Minidor  Delivery Van"],
  "FORCE MOTORS LIMTED,": [
    "TRAVELLER T2 SCHOOL  BUS",
    "TRUMP 40BS III PICK UP HSD",
  ],
  "Bharath Benz": ["BHARAT BENZ 914 BS3"],
  "SUNDARAM MOTORS": ["AL 1612/4210WB"],
  "DAIMMLER 1 COMM VEH P LTD": ["TIPPER"],
  "SWARAJ MAZDA LTD": ["SEMI  SALLON", "SEMI  SALLON", "WT 50 1. WB"],
  МАН: ["3118IL AL", "3118IL AL"],
  "MAHINDRA MAHINDRA LIMITED": ["MAHINDRA  MAX TRUCK"],
  "BAJAJ AUTO": [
    "BAJAJ 3 WHEELER  AUTORICKSHAW",
    "BAJAJ 3 WHEELER  AUTORICKSHAW",
  ],
  "TATA MOTORS LTD": ["TATA INFRA V30 NON AC BSVI"],
  "DAIMLER INDIA COMMERCIAL": [
    "Bharath benz 1215R BSVI",
    "Bharath benz 1215R BSVI-WHITE",
  ],
  "VE COMMERICAL VEHICLE LTD": ["EICHER 1090 L 40/P D BSIV"],
};

export const rtoList = {
  TN01: "RTO, CHENNAI (CENTRAL)",
  TN02: "RTO, CHENNAI (NORTH WEST)",
  TN03: "RTO, CHENNAI (NORTH EAST)",
  TN04: "RTO, CHENNAI (EAST)",
  TN05: "RT O, CHENNAI (NORTH)",
  TN06: "RTO, CHENNAI (SOUTH-EAST)",
  TN07: "RTO, CHENNAI(SOUTH)",
  TN09: "RTO, CHENNAI WEST.",
  TN10: "RTO, CHENNAI (SOUTH-WEST)",
  TN11: "RTO, TAMBARAM",
  TN12: "RTO, POONAMALLEE",
  TN13: "RTO, AMBATTUR",
  TN14: "RTO, SHOLINGANALLUR",
  TN15: "RTO, ULUNDURPET",
  TN15M: "RTO, KALAKURICHI",
  TN16: "RTO, TINDIVANAM",
  TN18: "RTO, REDHILLS",
  TN19: "RTO, CHENGALPET",
  TN20: "RTO, THIRUVALLUR",
  TN21: "RTO, KANCHEEPURAM",
  TN22: "RTO, MEENAMBAKKAM",
  TN23: "RTO, VELLORE",
  TN24: "RTO, KRISHNAGIRI",
  TN25: "RTO, TIRUVANNAMALAI",
  TN28: "RTO, NAMAKKKAL (NORTH)",
  TN29: "RTO, DHARMAPURI",
  TN30: "RTO, SALEM(WEST)",
  TN31: "RTO, CUDDALORE",
  TN32: "RTO, VILUPPURAM",
  TN33: "RTO, ERODE EAST",
  TN34: "RTO, TIRUCHENGODE",
  TN36: "RTO, GOBI",
  TN37: "RTO, COIMBATORE (SOUTH)",
  TN38: "RTO, COIMBATORE NORTH",
  TN39: "RTO, TIRUPUR NORTH",
  TN40: "RTO, METTUPALAYAM",
  TN41: "RTO, POLLACHI",
  TN42: "RTO, TIRUPUR SOUTH",
  TN43: "RTO, OOTY",
  TN45: "RTO, TRICHY WEST",
  TN46: "RTO, PERAMBALUR",
  TN47: "RTO, KARUR",
  TN48: "RTO, SRIRANGAM",
  TN49: "RTO, THANJAVUR",
  TN50: "RTO, TIRUVARUR",
  TN51: "RTO, NAGAPATTINAM",
  TN52: "RTO, SANKAGIRI",
  TN54: "RTO, SALEM(EAST)",
  TN55: "RTO, PUDUKKOTTAI",
  TN56: "RTO, PERUNDURAI",
  TN57: "RTO, DINDIGUL",
  TN58: "RTO, MADURAI(SOUTH)",
  TN59: "RTO, MADURAI (NORTH)",
  TN60: "RTO, THENI",
  TN61: "RTO, ARIYALUR",
  TN63: "RTO, SIVAGANGAI",
  TN64: "RTO, MADURAI (CENTRAL)",
  TN65: "RTO, RAMANATHAPURAM",
  TN66: "RTO, COIMBATORE (CENTRAL)",
  TN67: "RTO, VIRUDHUNAGAR",
  TN68: "RTO, KUMBAKONAM",
  TN69: "RTO, TUTICORIN",
  TN70: "RTO, HOSUR",
  TN72: "RTO, TIRUNELVELI",
  TN73: "RTO, RANIPET",
  TN74: "RTO, NAGERCOIL",
  TN75: "RTO, MARTHANDAM",
  TN76: "RT O, TENKASI",
  TN77: "RTO, ATTUR",
  TN78: "RTO, DHARAPURAM",
  TN79: "RTO, SANKARANKOVIL",
  TN81: "RTO, TRICHY(EAST)",
  TN82: "RTO, MAYILADUTHURAI",
  TN83: "RTO, VANIYAMBADI",
  TN83M: "RTO, TIRUPATTUR",
  TN84: "RTO, SRIVILLIPUTTUR",
  TN85: "RTO, KUNDRATHUR",
  TN86: "RTO, ERODE WEST",
  TN87: "RTO, SRIPERUMBUDUR",
  TN88: "RTO, NAMAKKAL SOUTH",
  TN90: "RTO, SALEM(SOUTH)",
  TN91: "RTO, CHIDHAMBRAM",
  TN92: "RTO, THIRUCHENDUR",
  TN93: "RTO, METTUR",
  TN94: "RTO, PALANI",
  TN95: "RTO, SIVAKASI",
  TN96: "RTO, KOVILPATTI",
  TN97: "RTO, ARANI",
  TN99: "RTO, COIMBATORE (WEST)",
  TN18Y: "UO, Gummidipoondi",
  TN20X: "UO,  Thiruthani",
  TN19Y: "UO,  Thirukalukundram",
  TN19Z: "UO,  Madhuranthagam",
  TN23T: "UO,  Gudiyatham",
  TN73z: "UO,  Arakkonam",
  TN83Y: "UO,  Ambur",
  TN36W: "UO,  Bhavani",
  TN36Z: "UO,  SATHYAMANGALAM",
  TN28Z: "UO,  RASIPURAM",
  TN88Z: "UO,  Paramathi velur",
  TN31Z: "UO,  Panruti",
  TN91Y: "UO,  Neyveli",
  TN91Z: "UO,  Viruthachalam",
  TN16Z: "UO, Gingee",
  TN97Z: "UO,  Cheyyar",
  TN45Z: "UO,  Manaparai",
  TN81Z: "UO,  Tiruverambur",
  TN48Z: "UO,  Thuraiyur",
  TN48Y: "UO,  MUSIRI",
  TN48X: "UO,  LALGUDI",
  TN47Z: "UO,  KULITHALAI",
  TN47Y: "UO,  Aravakurichi",
  TN47X: "UO,  Manmangalam",
  TN29W: "UO,  OMALUR",
  TN77Z: "UO,  VAZHAPADY",
  TN29Z: "UO,  HARUR",
  TN59W: "UO,  Melur",
  TN59V: "UO,  Vadipatti",
  TN58Z: "UO,  Thirumangalam",
  TN58Y: "UO,  Usilampatti",
  TN57Y: "UO,  Batlagundu",
  TN57V: "UO,  Vaedasandur",
  TN57S: "UO,  Natham",
  TN94Z: "UO,  Oddanchattram",
  TN60Z: "UO,  Uthamapalayam",
  TN49Y: "UO,  Pattukottai",
  TN50Z: "UO,  Mannargudi",
  TN50Y: "UO,  Thiruthuraipoondi",
  TN82Z: "UO,  Sirkali",
  TN55Z: "UO,  Aranthangi",
  TN55Y: "UO,  Illuppur",
  TN55X: "UO,  Alangudi",
  TN72U: "UO,  AMBASAMUDRAM",
  TN72V: "UO,  VALLIYOOR",
  TN37Z: "UO,  SULUR",
  TN39Z: "UO,  AVINASHI",
  TN42Y: "UO,  KANGEYAM",
  TN41W: "UO,  VALPARAI",
  TN67W: "UO,  GUDALUR",
  TN84U: "UO,  RAJAPALAYAM",
  TN63Z: "UO,  KARAIKUDI",
  TN65Z: "UO,  PARAMAKUDI",
  PY01: "PUDUCHERRY",
  PY02: "KARAIKAL",
  PY03: "МАНЕ",
  PY04: "YANAM",
  PY05: "OULGARET",
  PY05Z: "Thirubuvanai",
};
