export const tamilNaduRTOs = [
  { rtonum: "TN-01", rtoarea: "Chennai (Central)" },
  { rtonum: "TN-02", rtoarea: "Chennai (North West)" },
  { rtonum: "TN-03", rtoarea: "Chennai (North East)" },
  { rtonum: "TN-04", rtoarea: "Chennai (West)" },
  { rtonum: "TN-05", rtoarea: "Chennai (South West)" },
  { rtonum: "TN-06", rtoarea: "Chennai (South East)" },
  { rtonum: "TN-07", rtoarea: "Vellore" },
  { rtonum: "TN-09", rtoarea: "Krishnagiri" },
  { rtonum: "TN-10", rtoarea: "Kancheepuram" },
  { rtonum: "TN-11", rtoarea: "Tiruvallur" },
  { rtonum: "TN-12", rtoarea: "Salem" },
  { rtonum: "TN-13", rtoarea: "Dharmapuri" },
  { rtonum: "TN-14", rtoarea: "Cuddalore" },
  { rtonum: "TN-15", rtoarea: "Villupuram" },
  { rtonum: "TN-16", rtoarea: "Coimbatore (Central)" },
  { rtonum: "TN-17", rtoarea: "Coimbatore (North)" },
  { rtonum: "TN-18", rtoarea: "Coimbatore (South)" },
  { rtonum: "TN-19", rtoarea: "Tirupur" },
  { rtonum: "TN-20", rtoarea: "Erode" },
  { rtonum: "TN-21", rtoarea: "Tiruchirapalli" },
  { rtonum: "TN-22", rtoarea: "Karur" },
  { rtonum: "TN-23", rtoarea: "Perambalur" },
  { rtonum: "TN-24", rtoarea: "Madurai (Central)" },
  { rtonum: "TN-25", rtoarea: "Madurai (West)" },
  { rtonum: "TN-26", rtoarea: "Dindigul" },
  { rtonum: "TN-27", rtoarea: "Ramanathapuram" },
  { rtonum: "TN-28", rtoarea: "Sivagangai" },
  { rtonum: "TN-29", rtoarea: "Theni" },
  { rtonum: "TN-30", rtoarea: "Virudhunagar" },
  { rtonum: "TN-31", rtoarea: "Sivakasi" },
  { rtonum: "TN-32", rtoarea: "Tuticorin" },
  { rtonum: "TN-33", rtoarea: "Nagercoil" },
  { rtonum: "TN-34", rtoarea: "Kanyakumari" },
  { rtonum: "TN-35", rtoarea: "Namakkal" },
  { rtonum: "TN-36", rtoarea: "Thiruvarur" },
  { rtonum: "TN-37", rtoarea: "Nagapattinam" },
  { rtonum: "TN-38", rtoarea: "Thanjavur" },
  { rtonum: "TN-39", rtoarea: "Pudukkottai" },
  { rtonum: "TN-40", rtoarea: "Tirunelveli (Central)" },
  { rtonum: "TN-41", rtoarea: "Tirunelveli (West)" },
  { rtonum: "TN-42", rtoarea: "Tirunelveli (East)" },
  { rtonum: "TN-43", rtoarea: "Tirunelveli (South)" },
  { rtonum: "TN-45", rtoarea: "Chidambaram" },
  { rtonum: "TN-46", rtoarea: "Cumbum" },
  { rtonum: "TN-47", rtoarea: "Arakkonam" },
  { rtonum: "TN-48", rtoarea: "Sankarankovil" },
  { rtonum: "TN-49", rtoarea: "Usilampatti" },
  { rtonum: "TN-50", rtoarea: "Avadi" },
  { rtonum: "TN-51", rtoarea: "Kallakurichi" },
  { rtonum: "TN-52", rtoarea: "Rasipuram" },
  { rtonum: "TN-53", rtoarea: "Palani" },
  { rtonum: "TN-54", rtoarea: "Ambattur" },
  { rtonum: "TN-55", rtoarea: "Chengalpattu" },
  { rtonum: "TN-56", rtoarea: "Dharmapuri (North)" },
  { rtonum: "TN-57", rtoarea: "Gudiyatham" },
  { rtonum: "TN-58", rtoarea: "Uthukkottai" },
  { rtonum: "TN-59", rtoarea: "Thirupathur" },
  { rtonum: "TN-60", rtoarea: "Arni" },
  { rtonum: "TN-61", rtoarea: "Vaniyambadi" },
  { rtonum: "TN-62", rtoarea: "Krishnagiri (North)" },
  { rtonum: "TN-63", rtoarea: "Hosur" },
  { rtonum: "TN-64", rtoarea: "Vridhachalam" },
  { rtonum: "TN-65", rtoarea: "Gingee" },
  { rtonum: "TN-66", rtoarea: "Walajapet" },
  { rtonum: "TN-67", rtoarea: "Dharapuram" },
  { rtonum: "TN-68", rtoarea: "Udumalpet" },
  { rtonum: "TN-69", rtoarea: "Palayamkottai" },
  { rtonum: "TN-70", rtoarea: "Sankarankoil" },
  { rtonum: "TN-71", rtoarea: "Puliyangudi" },
  { rtonum: "TN-72", rtoarea: "Thiruchendur" },
  { rtonum: "TN-73", rtoarea: "Rajapalayam" },
  { rtonum: "TN-74", rtoarea: "Sivakasi (North)" },
  { rtonum: "TN-75", rtoarea: "Tenkasi" },
  { rtonum: "TN-76", rtoarea: "Ambur" },
  { rtonum: "TN-77", rtoarea: "Villupuram (North)" },
  { rtonum: "TN-78", rtoarea: "Rasipuram (South)" },
  { rtonum: "TN-79", rtoarea: "Aruppukottai" },
  { rtonum: "TN-80", rtoarea: "Cheyyar" },
  { rtonum: "TN-81", rtoarea: "Neyveli" },
  { rtonum: "TN-82", rtoarea: "Mayiladuthurai" },
  { rtonum: "TN-83", rtoarea: "Sirkazhi" },
  { rtonum: "TN-84", rtoarea: "Thiruvarur (North)" },
  { rtonum: "TN-85", rtoarea: "Thiruvannamalai" },
  { rtonum: "TN-86", rtoarea: "Villupuram (South)" },
  { rtonum: "TN-87", rtoarea: "Kumbakonam" },
  { rtonum: "TN-88", rtoarea: "Pattukottai" },
  { rtonum: "TN-89", rtoarea: "Thiruvaiyaru" },
  { rtonum: "TN-90", rtoarea: "Nannilam" },
  { rtonum: "TN-91", rtoarea: "Vedaranyam" },
  { rtonum: "TN-92", rtoarea: "Karaikkal" },
  { rtonum: "TN-93", rtoarea: "Pudukottai (North)" },
  { rtonum: "TN-94", rtoarea: "Perundurai" },
  { rtonum: "TN-95", rtoarea: "Kangayam" },
  { rtonum: "TN-96", rtoarea: "Palani (North)" },
  { rtonum: "TN-97", rtoarea: "Erode (North)" },
  { rtonum: "TN-98", rtoarea: "Tirupur (North)" },
  { rtonum: "TN-99", rtoarea: "Coimbatore (North East)" },
];
